config/routes.rb
LesHotel::Application.routes.draw do

  resources :hospedes

  

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/hospede.rb
class Hospede < ActiveRecord::Base

  def endereco
    "#{logradouro.split(" ").collect { |word| word.capitalize! }.join(' ')}, #{numero.capitalize!} #{complemento.capitalize!}"
  end
  def name=(name)
    @name = name.collect { |char| char.capitalize }.join
  end
  def cpf=(cpf)
    @cpf = sanitiza cpf
  end

  private
  def sanitiza(cpf)
    cpf.each_chr { |char| char.to_i.to_s }.join
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cliente }
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :endereco, :telefone)
    end
end

app/controllers/hospedes_controller.rb
class HospedesController < ApplicationController
  before_action :set_hospede, only: [:show, :edit, :update, :destroy]

  # GET /hospedes
  # GET /hospedes.json
  def index
    @hospedes = Hospede.all
  end

  # GET /hospedes/1
  # GET /hospedes/1.json
  def show
  end

  # GET /hospedes/new
  def new
    @hospede = Hospede.new
  end

  # GET /hospedes/1/edit
  def edit
  end

  # POST /hospedes
  # POST /hospedes.json
  def create
    @hospede = Hospede.new(hospede_params)

    respond_to do |format|
      if @hospede.save
        format.html { redirect_to @hospede, notice: 'Hospede was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hospede }
      else
        format.html { render action: 'new' }
        format.json { render json: @hospede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospedes/1
  # PATCH/PUT /hospedes/1.json
  def update
    respond_to do |format|
      if @hospede.update(hospede_params)
        format.html { redirect_to @hospede, notice: 'Hospede was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hospede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospedes/1
  # DELETE /hospedes/1.json
  def destroy
    @hospede.destroy
    respond_to do |format|
      format.html { redirect_to hospedes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospede
      @hospede = Hospede.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospede_params
      params.require(:hospede).permit(:cpf, :nome, :logradouro, :numero, :complemento, :bairro, :cidade, :estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/hospedes_helper.rb
module HospedesHelper

  def yield_docS 
    file = File.open("./my_file","w") { |content| content.puts "ok" }
  end
  
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.telefone %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cliente.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/hospedes/_form.html.erb
<%= form_for(@hospede) do |f| %>
  <% if @hospede.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospede.errors.count, "error") %> prohibited this hospede from being saved:</h2>
      <ul>
      <% @hospede.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="well span11">
    <div class="span3">
      <label for="hospede_cpf">CPF: </label>
      <input id="hospede_cpf" name="hospede[cpf]" type="text" class="input-block-level" />
    </div>
    <div class="span7">
      <label for="hospede_nome">Nome: </label>
      <input id="hospede_nome" name="hospede[nome]" type="text" class="input-block-level" />
    </div>
    <div class="span8">
      <label for="hospede_logradouro">Logradouro: </label>
      <input id="hospede_logradouro" name="hospede[logradouro]" type="text" class="input-block-level" />
    </div>
    <div class="span2">
      <label for="hospede_numero">Numero: </label>
      <input id="hospede_numero" name="hospede[numero]" type="text" class="input-block-level" />
    </div>
    <div class="span2">
      <label for="hospede_complemento">Complemento: </label>
      <input id="hospede_complemento" name="hospede[complemento]" type="text" class="input-block-level" />
    </div>
    <div class="span3">
      <label for="hospede_bairro">Bairro: </label>
      <input id="hospede_bairro" name="hospede[bairro]" type="text" class="input-block-level" />
    </div>
    <div class="span3">
      <label for="hospede_cidade">Cidade: </label>
      <input id="hospede_cidade" name="hospede[cidade]" type="text" class="input-block-level" />
    </div>
    <div class="span2">
      <label for="hospede_estado">Estado: </label>
      <input id="hospede_estado" name="hospede[estado]" type="text" class="input-block-level" />
    </div>
  </div>
  <div class="span11">
    <div class="span10">
      <div class="actions pull-right">
        <input type="submit" class="btn btn-info">
      </div>
	</div>
  </div>
<% end %>

app/views/hospedes/edit.html.erb
<% provide(:title, "| hospedes_edit") %>

<%= render 'form' %>

<%= link_to 'Show', @hospede %> |
<%= link_to 'Back', hospedes_path %>

app/views/hospedes/index.html.erb
  <% provide(:title, '| hospedes') %>
  <table class="table table-condensed table-hover table-bordered">
    <thead>
      <tr>
        <th>CPF</th>
        <th>Nome</th>
        <th>Endereco</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @hospedes.each do |hospede| %>
        <tr>
          <td><%= hospede.cpf %></td>
          <td><%= hospede.nome.split.each { |name| name.capitalize! }.join(" ") %></td>
	      <td><%= hospede.endereco %></td>
          <td><%= hospede.bairro.split.each { |name| name.capitalize! }.join(" ") %></td>
          <td><%= hospede.cidade.split.each { |name| name.capitalize! }.join(" ") %></td>
          <td><%= hospede.estado %></td>
          <td><%= link_to image_tag('glyphicons_150_edit.png'), edit_hospede_path(hospede) %></td>
          <td><%= link_to image_tag('glyphicons_207_remove_2.png'), hospede, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Cadastrar Hospede', new_hospede_path , :class => 'btn btn-primary' %>
  <br><br>
</div>

app/views/hospedes/new.html.erb
<div class="span6">
  <h3>Cadastrar Hospede</h3>
</div>
<%= render 'form' %>

app/views/hospedes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpf:</strong>
  <%= @hospede.cpf %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @hospede.nome %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @hospede.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @hospede.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @hospede.complemento %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @hospede.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @hospede.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @hospede.estado %>
</p>

<%= link_to 'Edit', edit_hospede_path(@hospede) %> |
<%= link_to 'Back', hospedes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LesHotel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
	    <a class="brand" href="#">les_hotel</a>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Cadastro Hospede", new_hospede_path %></li>
            <li><%= link_to "Registra Hospedagem",    '#' %></li>
            <li><%= link_to "Registra Reserva", '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="header-space"></div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>